/**
 * Pre-baked topic lists for common UK exams.
 * Used to detect known specs and suggest missing topics.
 * Key format: lowercase, normalised for fuzzy matching.
 */

export const SYLLABUS_TEMPLATES = [
  {
    id: 'aqa-alevel-maths',
    label: 'AQA A-Level Mathematics',
    matchKeywords: ['a-level math', 'a level math', 'alevel math', 'aqa math', 'a-level maths', 'a level maths', 'alevel maths', 'aqa maths'],
    topics: [
      'Algebra & Functions',
      'Quadratic Functions & Equations',
      'Equations & Inequalities',
      'Graphs & Transformations',
      'Straight Lines & Circles',
      'Algebraic Methods & Proof',
      'Binomial Expansion',
      'Trigonometric Ratios & Identities',
      'Trigonometric Equations',
      'Exponentials & Logarithms',
      'Differentiation — Fundamentals',
      'Differentiation — Chain, Product & Quotient Rules',
      'Differentiation — Applications',
      'Integration — Fundamentals',
      'Integration — Techniques',
      'Integration — Applications',
      'Vectors in 2D & 3D',
      'Sequences & Series',
      'Proof by Contradiction & Induction',
      'Parametric Equations',
      'Further Trigonometry',
      'Numerical Methods',
      'Statistical Sampling & Data',
      'Probability Distributions',
      'Normal Distribution',
      'Hypothesis Testing',
      'Kinematics',
      'Forces & Newton\'s Laws',
      'Moments & Statics',
      'Exam Strategy & Technique',
    ],
  },
  {
    id: 'aqa-alevel-biology',
    label: 'AQA A-Level Biology',
    matchKeywords: ['a-level bio', 'a level bio', 'alevel bio', 'aqa bio'],
    topics: [
      'Biological Molecules — Carbohydrates & Lipids',
      'Biological Molecules — Proteins & Enzymes',
      'Nucleic Acids & DNA',
      'Cell Structure & Microscopy',
      'Cell Membranes & Transport',
      'Cell Division — Mitosis & Meiosis',
      'Exchange Surfaces & Gas Exchange',
      'Mass Transport in Animals',
      'Mass Transport in Plants',
      'DNA Replication & Protein Synthesis',
      'Genetic Diversity & Inheritance',
      'Biodiversity & Classification',
      'Photosynthesis',
      'Respiration',
      'The Nervous System',
      'Hormonal Communication',
      'Homeostasis',
      'Populations & Ecosystems',
      'Gene Expression & Regulation',
      'Recombinant DNA Technology',
      'Exam Strategy & Technique',
    ],
  },
  {
    id: 'aqa-alevel-chemistry',
    label: 'AQA A-Level Chemistry',
    matchKeywords: ['a-level chem', 'a level chem', 'alevel chem', 'aqa chem'],
    topics: [
      'Atomic Structure & Mass Spectrometry',
      'Amount of Substance & Moles',
      'Bonding & Structure',
      'Energetics & Thermochemistry',
      'Kinetics & Rate of Reaction',
      'Chemical Equilibria & Le Chatelier',
      'Oxidation, Reduction & Redox',
      'Periodicity & Group Chemistry',
      'Transition Metals',
      'Alkanes & Halogenoalkanes',
      'Alkenes & Addition Polymers',
      'Alcohols & Carbonyl Compounds',
      'Carboxylic Acids & Derivatives',
      'Aromatic Chemistry',
      'Amines & Amino Acids',
      'Spectroscopy & Analysis',
      'Electrode Potentials & Electrochemistry',
      'Acids, Bases & Buffers',
      'Entropy & Gibbs Free Energy',
      'Exam Strategy & Technique',
    ],
  },
  {
    id: 'aqa-alevel-physics',
    label: 'AQA A-Level Physics',
    matchKeywords: ['a-level phys', 'a level phys', 'alevel phys', 'aqa phys'],
    topics: [
      'Measurements & Uncertainties',
      'Particles & Radiation',
      'Waves & Superposition',
      'Mechanics — Forces & Motion',
      'Mechanics — Energy & Power',
      'Electricity — Circuits & Resistance',
      'Electricity — EMF & Kirchhoff\'s Laws',
      'Further Mechanics — Circular Motion',
      'Further Mechanics — Oscillations',
      'Thermal Physics',
      'Fields — Gravitational',
      'Fields — Electric',
      'Fields — Magnetic',
      'Electromagnetic Induction',
      'Capacitors',
      'Nuclear Physics & Radioactivity',
      'Astrophysics',
      'Medical Physics',
      'Exam Strategy & Technique',
    ],
  },
  {
    id: 'aqa-gcse-maths',
    label: 'AQA GCSE Mathematics',
    matchKeywords: ['gcse math', 'gcse maths'],
    topics: [
      'Number — Fractions, Decimals & Percentages',
      'Number — Powers, Roots & Standard Form',
      'Algebra — Expressions & Equations',
      'Algebra — Quadratics & Inequalities',
      'Algebra — Graphs & Functions',
      'Algebra — Sequences',
      'Ratio, Proportion & Rates of Change',
      'Geometry — Properties of Shapes',
      'Geometry — Angles & Proofs',
      'Geometry — Transformations',
      'Geometry — Mensuration (Area & Volume)',
      'Trigonometry',
      'Pythagoras & Vectors',
      'Probability',
      'Statistics',
      'Exam Strategy & Technique',
    ],
  },
]

/**
 * Try to match an exam title to a known template.
 * Returns the matched template or null.
 */
export function matchTemplate(examTitle) {
  if (!examTitle) return null
  const lower = examTitle.toLowerCase()
  return SYLLABUS_TEMPLATES.find(t =>
    t.matchKeywords.some(kw => lower.includes(kw))
  ) || null
}
